# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

# ARM FVP RD-v1
base_arch fvp
base_arch armv8

cflags -mcpu=neoverse-v1+nosve
ldflags -mcpu=neoverse-v1

configs PLATFORM_FVP=1

configs PLATFORM_SVM_IPA_BASE=0x28800000
configs PLATFORM_SVM_IPA_SIZE=0x07ffffff

configs PLATFORM_GLOBAL_IRQ_ALLOC_BASE=960U

configs CONFIG_WATCHDOG_BARK_VIRQ=32
configs CONFIG_WATCHDOG_BITE_VIRQ=33

# Let RM configure vPCI for HLOS Virtio-iommu
# This should be used when SMMUv3 is enabled in Hypervisor as it modifies the base DT
configs PLATFORM_HLOS_NEEDS_VPCI=1
configs PLATFORM_HLOS_VPCI_LINUX_DOMAIN=0x8000
configs PLATFORM_HLOS_GIC_ADDRESS_CELLS=2U

# Virtio IOMMU settings from RM
# We probably only want one virtio-iommu instance per SMMU in the VM, but test multiple
# here as we will end up with multiple Virtio-iommu instances pointing to the same SMMU HW
# Also, later it might be interesting to have seperate instances for specific use-cases that can
# then limit or have some different preset config.
configs PLATFORM_HLOS_VIRTIO_IOMMU_NUM_INSTANCES=1
# Limit how many streams can be allocated by a Virtio-iommu instance
# This is to prevent guests from using too much memory.
configs PLATFORM_HLOS_VIRTIO_IOMMU_MAX_STREAMS=10

sub_directory platform/fvp/target/fvp
