# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

configs PLATFORM_QEMU=1

configs LOG_AREA_SIZE=8192

sub_directory platform/qemu
sub_directory platform/stubs
sub_directory platform/arm_pl011
