# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

include include

source src/smc.c
source src/timestamp.c
source src/cache.c
source src/vm_mgnt_arch.c
source src/ffa/ffa.c

configs PAGE_BITS=12U
configs PAGE_SIZE=4096U
configs LARGE_PAGE_SIZE=2097152U
